### ISSUE TITLE
repository abandoned?

### ISSUE THREAD

**Issue by khimaros** [rustodon/rustodon#230]
There have been no commits from humans since April. Is development happening elsewhere or has this project been abandoned?

**Comment by barzamin** [comment]
I'm dissatisifed with the backend direction I've been taking and I've been working on some new ideas offline; additionally, there's a few more recently updated feature branches. I want this project to become something very different than the existing fediverse software, and I've held off on actually doing stuff in the repo because it 1) i'm still just toying around with tools and ideas and 2) it's a very major change. I also want to rename from Rustodon because that sounds 1) like a mastodon clone and 2) like I'm trying to play up the fact it's written in Rust. 

I work on this project when I have bursts of motivation and time basically abandon it otherwise. That's not a super great strategy! Motivation and time also don't line up very often; it's very common that I have plenty of time and want to work on something else, or I'm very excited about Rustodon but have work to do for jobs/classes.

This is a fairly long and rambly response to a simple question, sorry! **The tl;dr** is that Rustodon is **not dead**, I'm just **brainstorming ways to rearchitect**.

/cc @khimaros
