### ISSUE TITLE
Got 404 for /nodeinfo/2.0 route

### ISSUE THREAD

**Issue by dfgweb** [rustodon/rustodon#272]
The `/nodeinfo/2.0` URI return a 404 status.
According to the log of my running instance, the `/nodeinfo/2.0` URI isn't routed to the right function.

```
Aug 09 10:22:55 vps627835 rustodon[22760]: Aug 09 10:22:55.316 INFO request, uri: "/.well-known/nodeinfo", method: Get
Aug 09 10:22:55 vps627835 rustodon[22760]: Aug 09 10:22:55.317 INFO response, status: 200 OK, route: GET /.well-known/nodeinfo (webfinger_nodeinfo)
Aug 09 10:23:43 vps627835 rustodon[22760]: Aug 09 10:23:43.149 INFO request, uri: "/nodeinfo/2.0", method: Get
Aug 09 10:23:43 vps627835 rustodon[22760]: Aug 09 10:23:43.153 INFO response, status: 404 Not Found, route: GET /<username>/<status_id> [2] text/html (status_page_simple)
```

**Comment by barzamin** [comment]
That's extremely strange! Can you manually run `curl https://your.instance/nodeinfo/2.0`? I can't reproduce this locally; the route is working fine for me

**Comment by barzamin** [comment]
Can you paste the result of `grep rocket Cargo.lock | head -n1`, too?

**Comment by dfgweb** [comment]
Good catch! It works with `curl` !

```
Aug 11 18:51:30 vps627835 rustodon[22760]: Aug 11 18:51:30.279 INFO request, uri: "/nodeinfo/2.0", method: Get
Aug 11 18:51:30 vps627835 rustodon[22760]: Aug 11 18:51:30.282 INFO response, status: 200 OK, route: GET /nodeinfo/2.0 application/json (nodeinfo)
Aug 11 18:52:58 vps627835 rustodon[22760]: Aug 11 18:52:58.847 INFO request, uri: "/nodeinfo/2.0", method: Get
Aug 11 18:52:58 vps627835 rustodon[22760]: Aug 11 18:52:58.851 INFO response, status: 404 Not Found, route: GET /<username>/<status_id> [2] text/html (status_page_simple)

```
The first request is curl. The second one is Firefox.

**Comment by dfgweb** [comment]
So this may be a normal behaviour, but it is strange this don't work with FF (which display JSON relay nicely) (`https://rstdn.int21h.eu/.well-known/nodeinfo` display well for example).

**Comment by dfgweb** [comment]
```
~/rustodon$ grep rocket Cargo.lock | head -n1
 "rocket 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)",
```

**Comment by dfgweb** [comment]
May be related to `content-type`. FF may expect `text/*` and add a header for this.

**Comment by dfgweb** [comment]
After patching well_known.rs with the following patch, I can access this URI with FF now.

```
diff --git a/src/routes/well_known.rs b/src/routes/well_known.rs
index b82f675..74eb493 100644
--- a/src/routes/well_known.rs
+++ b/src/routes/well_known.rs
@@ -91,7 +91,7 @@ pub fn webfinger_nodeinfo() -> Content<JsonValue> {
     Content(jrd_ctype, JsonValue(doc))
 }
 
-#[get("/nodeinfo/2.0", format = "application/json")]
+#[get("/nodeinfo/2.0")]
 pub fn nodeinfo(db_conn: db::Connection) -> Result<Content<JsonValue>, Error> {
     let ctype = ContentType::with_params(
         "application",
```

**Comment by dfgweb** [comment]
I can see that FF add the following header to the request (third tab in json display), that conflict with the route configuration.
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

**Comment by dfgweb** [comment]
So, problem is narrowed. 
- Rocket routes which specify a content-type may result in problems depending on client type and request they made,
- Firefox may be a useful client to show json result of API routes that will be required to use Mastodon client with rustodon (Mammut crate, Fedilab or another android client)

I will push a small pull request for this.

**Comment by dfgweb** [comment]
Last note. According to Rocket documentation, specifying a format for a GET request will result in Rocket check the `Accept` header and the specified format MUST be the preferred accepted content-type.

**Comment by barzamin** [comment]
Thanks for the careful review! I did a bit more looking, and I think I figured out exactly what's going on.
# To sum up:
* Firefox defaults to `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`. This would normally be fine, since it has `*/*` (weighted at 0.8) in the accept string and thus responding with `application/json` is valid
* However, Rocket does the check on GET requests (well, anything that _doesn't_ accept a request body) [like this](https://github.com/SergioBenitez/Rocket/blob/da7e022f990e0b8e8201b0a359a43104686ff1a4/core/lib/src/router/collider.rs#L131), which just looks at _media types_ (eg `text/html`).
  * The request media types comes from [`Request::format()`](https://github.com/SergioBenitez/Rocket/blob/da7e022f990e0b8e8201b0a359a43104686ff1a4/core/lib/src/request/request.rs#L454) (note the FIXME); this _only looks at the preferred format_ in the `Accept` header and _none of the following ones_.

# Fixing this
I would really really really prefer keeping the behavior the way it is. I don't particularly like making a route that's _nominally_ supposed to respond with JSON happily listen to a `text/html` request; none of the ActivityPub endpoints do, at any rate.

**However**, I would be very happy if you implemented something like what Mastodon does, wherein adding a `.json` to the URL forces JSON to be returned. Mastodon does this on (almost) all JSON-responding routes, and it's helpful for debugging in exactly the way you mentioned.

**Comment by dfgweb** [comment]
A useful implementation should be included inside Rocket (as a route option) to avoid routes to be duplicate in Rocket's client code.

I'm just starting to learn Rust (after so many other languages), so it could be a nice thing to try, but it won't be the first. ;-)
