### ISSUE TITLE
Necessity of DOMAIN and https in development

### ISSUE THREAD

**Issue by netshade** [rustodon/rustodon#62]
When testing basic functionality (assumed: `ROCKET_ENV` == `development`), it seems like the default `https` protocol and requirement for `DOMAIN` to be explicitly set could be relaxed. 

Does it seem reasonable to make it such that in `development`:

`DOMAIN` defaults to `localhost` and the bound Rocket port

Additionally, instead of using `https` for protocols, the leading protocol adopted is `//`, to bias to the browser's protocol that is used to connect to the site?

**Comment by netshade** [comment]
After looking at it some more, it seems like the implementations of `get_url` that use `BASE_URL` could just omit the leading URL portion and link to the path, and the right thing should? happen based on usage. Or is there something more desirable about having all the `_endpoint` methods return a true URL?

**Comment by barzamin** [comment]
when you're developing locally, just using localhost:port is fine. which is what i was doing, until i started testing federation against mastodon, which breaks - since rocket isn't serving over ssl, and webfinger is ssl-only. there's probably a nicer way to do this, tbh!

> After looking at it some more, it seems like the implementations of get_url that use BASE_URL could just omit the leading URL portion and link to the path, and the right thing should? happen based on usage. Or is there something more desirable about having all the _endpoint methods return a URL that always includes the desired host?

note how all the endpoint methods get serialized into the [activitypub representations](https://github.com/rustodon/rustodon/blob/master/src/activitypub/mod.rs#L86) of things. those endpoints are for other servers to use, so we need to make sure they can find us

**Comment by barzamin** [comment]
> It seems like the second invoking the machinery of the first is unnecessary; like, the templates should always be referring to domain'less representations when it comes to linking to on site resources.

Yes, that's probably a good idea! I'm planning to wait for the upcoming Rocket get-path-to-a-route functionality before changing that, though.

> Do I understand it correctly in that there may be Account's that are representing off-server users whose persisted uri is the understood means of accessing an inbox or outbox, but that it is implied that for any given Rustodon account, a URI shall always be None, and that this is how the default paths are expressed?

Yep, exactly. We should've documented this better!
